version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./data/mongo:/data/db
      - ./data/queries:/queries
      - ./data/logs:/logs